before:
  hooks:
    - go mod tidy
builds:
  -
    id: ovcs-linux
    binary: ovcs
    ldflags:
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
  -
    id: ovcs-other
    binary: ovcs
    ldflags:
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - windows
      - freebsd
    goarch:
      - '386'
      - amd64
      - arm
      - arm64

archives:
  -
    id: ovcs-archives
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
    - ovcs-linux
    - ovcs-other
    format: zip

nfpms:
  -
    id: ovcs-nfpms
    builds:
    - ovcs-linux
    homepage: https://github.com/noborus/ovcs
    maintainer: Noboru Saito <noborusai@gmail.com>
    description: The client/server of the terminal pager ov.
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin

brews:
  -
    name: ovcs
    tap:
      owner: noborus
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    commit_author:
      name: noborus
      email: noborusai@gmail.com
    homepage: https://github.com/noborus/ovcs
    description: "The client/server of the terminal pager ov"
    test:
      system "#{bin}/ovcs version"
    install:
      bin.install "ovcs"
